"""create appointments table

Revision ID: 7121b123c2ac
Revises: 9515268d219b
Create Date: 2025-09-10 09:58:59.630104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7121b123c2ac'
down_revision = '9515268d219b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_no', sa.String(), nullable=True))
        batch_op.drop_column('Patient_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Patient_no', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('patient_no')

    op.drop_table('appointments')
    # ### end Alembic commands ###
